### Access root url
get http://localhost:{{$dotenv PORT}}
Authorization: Bearer {{$dotenv BEARER_EXAMPLE}}

### signup w/ email and password
post http://localhost:{{$dotenv PORT}}/signup
Content-Type: application/json

{
    "id": "email@example.com",
    "password": "password"
}

### signup w/ phone number and password
post http://localhost:{{$dotenv PORT}}/signup
Content-Type: application/json

{
    "id": "+77771112233",
    "password": "password"
}

### signin
post http://localhost:{{$dotenv PORT}}/signin
Content-Type: application/json

{
    "id": "email@example.com",
    "password": "password"
}

### refresh access token
post http://localhost:{{$dotenv PORT}}/signin/new_token
Content-Type: application/json

### get user info
get http://localhost:{{$dotenv PORT}}/info
Authorization: Bearer {{$dotenv BEARER_EXAMPLE}}
